#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CongTyDuocPham.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WEBCONGTYDUOCPHAM")]
	public partial class Data_CongTyDuocPhamDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_HOADON(CT_HOADON instance);
    partial void UpdateCT_HOADON(CT_HOADON instance);
    partial void DeleteCT_HOADON(CT_HOADON instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertCT_PHIEUNHAPKHO(CT_PHIEUNHAPKHO instance);
    partial void UpdateCT_PHIEUNHAPKHO(CT_PHIEUNHAPKHO instance);
    partial void DeleteCT_PHIEUNHAPKHO(CT_PHIEUNHAPKHO instance);
    partial void InsertCHI_TIET_DUOCPHAM(CHI_TIET_DUOCPHAM instance);
    partial void UpdateCHI_TIET_DUOCPHAM(CHI_TIET_DUOCPHAM instance);
    partial void DeleteCHI_TIET_DUOCPHAM(CHI_TIET_DUOCPHAM instance);
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertDANHMUC(DANHMUC instance);
    partial void UpdateDANHMUC(DANHMUC instance);
    partial void DeleteDANHMUC(DANHMUC instance);
    partial void InsertDUOCPHAM(DUOCPHAM instance);
    partial void UpdateDUOCPHAM(DUOCPHAM instance);
    partial void DeleteDUOCPHAM(DUOCPHAM instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAIDUOCPHAM(LOAIDUOCPHAM instance);
    partial void UpdateLOAIDUOCPHAM(LOAIDUOCPHAM instance);
    partial void DeleteLOAIDUOCPHAM(LOAIDUOCPHAM instance);
    partial void InsertLOAIHINH(LOAIHINH instance);
    partial void UpdateLOAIHINH(LOAIHINH instance);
    partial void DeleteLOAIHINH(LOAIHINH instance);
    partial void InsertLOAIKHACHHANG(LOAIKHACHHANG instance);
    partial void UpdateLOAIKHACHHANG(LOAIKHACHHANG instance);
    partial void DeleteLOAIKHACHHANG(LOAIKHACHHANG instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHIEUNHAPKHO(PHIEUNHAPKHO instance);
    partial void UpdatePHIEUNHAPKHO(PHIEUNHAPKHO instance);
    partial void DeletePHIEUNHAPKHO(PHIEUNHAPKHO instance);
    #endregion
		
		public Data_CongTyDuocPhamDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WEBCONGTYDUOCPHAMConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Data_CongTyDuocPhamDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_CongTyDuocPhamDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_CongTyDuocPhamDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_CongTyDuocPhamDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_HOADON> CT_HOADONs
		{
			get
			{
				return this.GetTable<CT_HOADON>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<CT_PHIEUNHAPKHO> CT_PHIEUNHAPKHOs
		{
			get
			{
				return this.GetTable<CT_PHIEUNHAPKHO>();
			}
		}
		
		public System.Data.Linq.Table<CHI_TIET_DUOCPHAM> CHI_TIET_DUOCPHAMs
		{
			get
			{
				return this.GetTable<CHI_TIET_DUOCPHAM>();
			}
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<DANHMUC> DANHMUCs
		{
			get
			{
				return this.GetTable<DANHMUC>();
			}
		}
		
		public System.Data.Linq.Table<DUOCPHAM> DUOCPHAMs
		{
			get
			{
				return this.GetTable<DUOCPHAM>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAIDUOCPHAM> LOAIDUOCPHAMs
		{
			get
			{
				return this.GetTable<LOAIDUOCPHAM>();
			}
		}
		
		public System.Data.Linq.Table<LOAIHINH> LOAIHINHs
		{
			get
			{
				return this.GetTable<LOAIHINH>();
			}
		}
		
		public System.Data.Linq.Table<LOAIKHACHHANG> LOAIKHACHHANGs
		{
			get
			{
				return this.GetTable<LOAIKHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAPKHO> PHIEUNHAPKHOs
		{
			get
			{
				return this.GetTable<PHIEUNHAPKHO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_HOADON")]
	public partial class CT_HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_HOADON;
		
		private int _ID_DUOCPHAM;
		
		private int _SOLUONG;
		
		private System.Nullable<double> _DONGIA;
		
		private EntityRef<DUOCPHAM> _DUOCPHAM;
		
		private EntityRef<HOADON> _HOADON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_HOADONChanging(int value);
    partial void OnID_HOADONChanged();
    partial void OnID_DUOCPHAMChanging(int value);
    partial void OnID_DUOCPHAMChanged();
    partial void OnSOLUONGChanging(int value);
    partial void OnSOLUONGChanged();
    partial void OnDONGIAChanging(System.Nullable<double> value);
    partial void OnDONGIAChanged();
    #endregion
		
		public CT_HOADON()
		{
			this._DUOCPHAM = default(EntityRef<DUOCPHAM>);
			this._HOADON = default(EntityRef<HOADON>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HOADON", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_HOADON
		{
			get
			{
				return this._ID_HOADON;
			}
			set
			{
				if ((this._ID_HOADON != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_HOADONChanging(value);
					this.SendPropertyChanging();
					this._ID_HOADON = value;
					this.SendPropertyChanged("ID_HOADON");
					this.OnID_HOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DUOCPHAM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_DUOCPHAM
		{
			get
			{
				return this._ID_DUOCPHAM;
			}
			set
			{
				if ((this._ID_DUOCPHAM != value))
				{
					if (this._DUOCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DUOCPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_DUOCPHAM = value;
					this.SendPropertyChanged("ID_DUOCPHAM");
					this.OnID_DUOCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int NOT NULL")]
		public int SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Float")]
		public System.Nullable<double> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DUOCPHAM_CT_HOADON", Storage="_DUOCPHAM", ThisKey="ID_DUOCPHAM", OtherKey="ID_DUOCPHAM", IsForeignKey=true)]
		public DUOCPHAM DUOCPHAM
		{
			get
			{
				return this._DUOCPHAM.Entity;
			}
			set
			{
				DUOCPHAM previousValue = this._DUOCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._DUOCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DUOCPHAM.Entity = null;
						previousValue.CT_HOADONs.Remove(this);
					}
					this._DUOCPHAM.Entity = value;
					if ((value != null))
					{
						value.CT_HOADONs.Add(this);
						this._ID_DUOCPHAM = value.ID_DUOCPHAM;
					}
					else
					{
						this._ID_DUOCPHAM = default(int);
					}
					this.SendPropertyChanged("DUOCPHAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CT_HOADON", Storage="_HOADON", ThisKey="ID_HOADON", OtherKey="ID_HOADON", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CT_HOADONs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CT_HOADONs.Add(this);
						this._ID_HOADON = value.ID_HOADON;
					}
					else
					{
						this._ID_HOADON = default(int);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_USER;
		
		private string _PASS;
		
		private string _TRANGTHAI;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USERChanging(string value);
    partial void OnID_USERChanged();
    partial void OnPASSChanging(string value);
    partial void OnPASSChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PASS
		{
			get
			{
				return this._PASS;
			}
			set
			{
				if ((this._PASS != value))
				{
					this.OnPASSChanging(value);
					this.SendPropertyChanging();
					this._PASS = value;
					this.SendPropertyChanged("PASS");
					this.OnPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="VarChar(10)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_KHACHHANG", Storage="_KHACHHANGs", ThisKey="ID_USER", OtherKey="EMAIL")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_NHANVIEN", Storage="_NHANVIENs", ThisKey="ID_USER", OtherKey="EMAIL")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_PHIEUNHAPKHO")]
	public partial class CT_PHIEUNHAPKHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PHIEUNHAPKHO;
		
		private int _ID_DUOCPHAM;
		
		private System.Nullable<int> _SO_LUONG;
		
		private EntityRef<DUOCPHAM> _DUOCPHAM;
		
		private EntityRef<PHIEUNHAPKHO> _PHIEUNHAPKHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PHIEUNHAPKHOChanging(int value);
    partial void OnID_PHIEUNHAPKHOChanged();
    partial void OnID_DUOCPHAMChanging(int value);
    partial void OnID_DUOCPHAMChanged();
    partial void OnSO_LUONGChanging(System.Nullable<int> value);
    partial void OnSO_LUONGChanged();
    #endregion
		
		public CT_PHIEUNHAPKHO()
		{
			this._DUOCPHAM = default(EntityRef<DUOCPHAM>);
			this._PHIEUNHAPKHO = default(EntityRef<PHIEUNHAPKHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PHIEUNHAPKHO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PHIEUNHAPKHO
		{
			get
			{
				return this._ID_PHIEUNHAPKHO;
			}
			set
			{
				if ((this._ID_PHIEUNHAPKHO != value))
				{
					if (this._PHIEUNHAPKHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PHIEUNHAPKHOChanging(value);
					this.SendPropertyChanging();
					this._ID_PHIEUNHAPKHO = value;
					this.SendPropertyChanged("ID_PHIEUNHAPKHO");
					this.OnID_PHIEUNHAPKHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DUOCPHAM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_DUOCPHAM
		{
			get
			{
				return this._ID_DUOCPHAM;
			}
			set
			{
				if ((this._ID_DUOCPHAM != value))
				{
					if (this._DUOCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DUOCPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_DUOCPHAM = value;
					this.SendPropertyChanged("ID_DUOCPHAM");
					this.OnID_DUOCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_LUONG", DbType="Int")]
		public System.Nullable<int> SO_LUONG
		{
			get
			{
				return this._SO_LUONG;
			}
			set
			{
				if ((this._SO_LUONG != value))
				{
					this.OnSO_LUONGChanging(value);
					this.SendPropertyChanging();
					this._SO_LUONG = value;
					this.SendPropertyChanged("SO_LUONG");
					this.OnSO_LUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DUOCPHAM_CT_PHIEUNHAPKHO", Storage="_DUOCPHAM", ThisKey="ID_DUOCPHAM", OtherKey="ID_DUOCPHAM", IsForeignKey=true)]
		public DUOCPHAM DUOCPHAM
		{
			get
			{
				return this._DUOCPHAM.Entity;
			}
			set
			{
				DUOCPHAM previousValue = this._DUOCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._DUOCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DUOCPHAM.Entity = null;
						previousValue.CT_PHIEUNHAPKHOs.Remove(this);
					}
					this._DUOCPHAM.Entity = value;
					if ((value != null))
					{
						value.CT_PHIEUNHAPKHOs.Add(this);
						this._ID_DUOCPHAM = value.ID_DUOCPHAM;
					}
					else
					{
						this._ID_DUOCPHAM = default(int);
					}
					this.SendPropertyChanged("DUOCPHAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAPKHO_CT_PHIEUNHAPKHO", Storage="_PHIEUNHAPKHO", ThisKey="ID_PHIEUNHAPKHO", OtherKey="ID_PHIEUNHAPKHO", IsForeignKey=true)]
		public PHIEUNHAPKHO PHIEUNHAPKHO
		{
			get
			{
				return this._PHIEUNHAPKHO.Entity;
			}
			set
			{
				PHIEUNHAPKHO previousValue = this._PHIEUNHAPKHO.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUNHAPKHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUNHAPKHO.Entity = null;
						previousValue.CT_PHIEUNHAPKHOs.Remove(this);
					}
					this._PHIEUNHAPKHO.Entity = value;
					if ((value != null))
					{
						value.CT_PHIEUNHAPKHOs.Add(this);
						this._ID_PHIEUNHAPKHO = value.ID_PHIEUNHAPKHO;
					}
					else
					{
						this._ID_PHIEUNHAPKHO = default(int);
					}
					this.SendPropertyChanged("PHIEUNHAPKHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHI_TIET_DUOCPHAM")]
	public partial class CHI_TIET_DUOCPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_THONGTIN_CHINH_DUOCPHAM;
		
		private int _ID_DUOCPHAM;
		
		private string _CONGDUNG;
		
		private string _LIEUDUNG;
		
		private string _DUONG_DUNG;
		
		private string _HAM_LUONG;
		
		private string _DANG_BAO_CHE;
		
		private string _HOAT_CHAT;
		
		private System.Nullable<System.DateTime> _HAN_DUNG;
		
		private string _QUA_LIEU_VA_XU_LY;
		
		private string _CANH_GIAC_DUOC;
		
		private string _TUONG_TAC_THUOC;
		
		private string _DIEU_KIEN_BAO_QUAN;
		
		private string _CHONG_CHI_DINH;
		
		private string _TAC_DUNG_PHU;
		
		private string _PHAM_VI_PHAN_PHOI;
		
		private string _XUAT_XU;
		
		private EntityRef<DUOCPHAM> _DUOCPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_THONGTIN_CHINH_DUOCPHAMChanging(int value);
    partial void OnID_THONGTIN_CHINH_DUOCPHAMChanged();
    partial void OnID_DUOCPHAMChanging(int value);
    partial void OnID_DUOCPHAMChanged();
    partial void OnCONGDUNGChanging(string value);
    partial void OnCONGDUNGChanged();
    partial void OnLIEUDUNGChanging(string value);
    partial void OnLIEUDUNGChanged();
    partial void OnDUONG_DUNGChanging(string value);
    partial void OnDUONG_DUNGChanged();
    partial void OnHAM_LUONGChanging(string value);
    partial void OnHAM_LUONGChanged();
    partial void OnDANG_BAO_CHEChanging(string value);
    partial void OnDANG_BAO_CHEChanged();
    partial void OnHOAT_CHATChanging(string value);
    partial void OnHOAT_CHATChanged();
    partial void OnHAN_DUNGChanging(System.Nullable<System.DateTime> value);
    partial void OnHAN_DUNGChanged();
    partial void OnQUA_LIEU_VA_XU_LYChanging(string value);
    partial void OnQUA_LIEU_VA_XU_LYChanged();
    partial void OnCANH_GIAC_DUOCChanging(string value);
    partial void OnCANH_GIAC_DUOCChanged();
    partial void OnTUONG_TAC_THUOCChanging(string value);
    partial void OnTUONG_TAC_THUOCChanged();
    partial void OnDIEU_KIEN_BAO_QUANChanging(string value);
    partial void OnDIEU_KIEN_BAO_QUANChanged();
    partial void OnCHONG_CHI_DINHChanging(string value);
    partial void OnCHONG_CHI_DINHChanged();
    partial void OnTAC_DUNG_PHUChanging(string value);
    partial void OnTAC_DUNG_PHUChanged();
    partial void OnPHAM_VI_PHAN_PHOIChanging(string value);
    partial void OnPHAM_VI_PHAN_PHOIChanged();
    partial void OnXUAT_XUChanging(string value);
    partial void OnXUAT_XUChanged();
    #endregion
		
		public CHI_TIET_DUOCPHAM()
		{
			this._DUOCPHAM = default(EntityRef<DUOCPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_THONGTIN_CHINH_DUOCPHAM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_THONGTIN_CHINH_DUOCPHAM
		{
			get
			{
				return this._ID_THONGTIN_CHINH_DUOCPHAM;
			}
			set
			{
				if ((this._ID_THONGTIN_CHINH_DUOCPHAM != value))
				{
					this.OnID_THONGTIN_CHINH_DUOCPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_THONGTIN_CHINH_DUOCPHAM = value;
					this.SendPropertyChanged("ID_THONGTIN_CHINH_DUOCPHAM");
					this.OnID_THONGTIN_CHINH_DUOCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DUOCPHAM", DbType="Int NOT NULL")]
		public int ID_DUOCPHAM
		{
			get
			{
				return this._ID_DUOCPHAM;
			}
			set
			{
				if ((this._ID_DUOCPHAM != value))
				{
					if (this._DUOCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DUOCPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_DUOCPHAM = value;
					this.SendPropertyChanged("ID_DUOCPHAM");
					this.OnID_DUOCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONGDUNG", DbType="NVarChar(MAX)")]
		public string CONGDUNG
		{
			get
			{
				return this._CONGDUNG;
			}
			set
			{
				if ((this._CONGDUNG != value))
				{
					this.OnCONGDUNGChanging(value);
					this.SendPropertyChanging();
					this._CONGDUNG = value;
					this.SendPropertyChanged("CONGDUNG");
					this.OnCONGDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIEUDUNG", DbType="NVarChar(MAX)")]
		public string LIEUDUNG
		{
			get
			{
				return this._LIEUDUNG;
			}
			set
			{
				if ((this._LIEUDUNG != value))
				{
					this.OnLIEUDUNGChanging(value);
					this.SendPropertyChanging();
					this._LIEUDUNG = value;
					this.SendPropertyChanged("LIEUDUNG");
					this.OnLIEUDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUONG_DUNG", DbType="NVarChar(MAX)")]
		public string DUONG_DUNG
		{
			get
			{
				return this._DUONG_DUNG;
			}
			set
			{
				if ((this._DUONG_DUNG != value))
				{
					this.OnDUONG_DUNGChanging(value);
					this.SendPropertyChanging();
					this._DUONG_DUNG = value;
					this.SendPropertyChanged("DUONG_DUNG");
					this.OnDUONG_DUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAM_LUONG", DbType="NVarChar(MAX)")]
		public string HAM_LUONG
		{
			get
			{
				return this._HAM_LUONG;
			}
			set
			{
				if ((this._HAM_LUONG != value))
				{
					this.OnHAM_LUONGChanging(value);
					this.SendPropertyChanging();
					this._HAM_LUONG = value;
					this.SendPropertyChanged("HAM_LUONG");
					this.OnHAM_LUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANG_BAO_CHE", DbType="NVarChar(MAX)")]
		public string DANG_BAO_CHE
		{
			get
			{
				return this._DANG_BAO_CHE;
			}
			set
			{
				if ((this._DANG_BAO_CHE != value))
				{
					this.OnDANG_BAO_CHEChanging(value);
					this.SendPropertyChanging();
					this._DANG_BAO_CHE = value;
					this.SendPropertyChanged("DANG_BAO_CHE");
					this.OnDANG_BAO_CHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOAT_CHAT", DbType="NVarChar(MAX)")]
		public string HOAT_CHAT
		{
			get
			{
				return this._HOAT_CHAT;
			}
			set
			{
				if ((this._HOAT_CHAT != value))
				{
					this.OnHOAT_CHATChanging(value);
					this.SendPropertyChanging();
					this._HOAT_CHAT = value;
					this.SendPropertyChanged("HOAT_CHAT");
					this.OnHOAT_CHATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAN_DUNG", DbType="Date")]
		public System.Nullable<System.DateTime> HAN_DUNG
		{
			get
			{
				return this._HAN_DUNG;
			}
			set
			{
				if ((this._HAN_DUNG != value))
				{
					this.OnHAN_DUNGChanging(value);
					this.SendPropertyChanging();
					this._HAN_DUNG = value;
					this.SendPropertyChanged("HAN_DUNG");
					this.OnHAN_DUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUA_LIEU_VA_XU_LY", DbType="NVarChar(MAX)")]
		public string QUA_LIEU_VA_XU_LY
		{
			get
			{
				return this._QUA_LIEU_VA_XU_LY;
			}
			set
			{
				if ((this._QUA_LIEU_VA_XU_LY != value))
				{
					this.OnQUA_LIEU_VA_XU_LYChanging(value);
					this.SendPropertyChanging();
					this._QUA_LIEU_VA_XU_LY = value;
					this.SendPropertyChanged("QUA_LIEU_VA_XU_LY");
					this.OnQUA_LIEU_VA_XU_LYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANH_GIAC_DUOC", DbType="NVarChar(MAX)")]
		public string CANH_GIAC_DUOC
		{
			get
			{
				return this._CANH_GIAC_DUOC;
			}
			set
			{
				if ((this._CANH_GIAC_DUOC != value))
				{
					this.OnCANH_GIAC_DUOCChanging(value);
					this.SendPropertyChanging();
					this._CANH_GIAC_DUOC = value;
					this.SendPropertyChanged("CANH_GIAC_DUOC");
					this.OnCANH_GIAC_DUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUONG_TAC_THUOC", DbType="NVarChar(MAX)")]
		public string TUONG_TAC_THUOC
		{
			get
			{
				return this._TUONG_TAC_THUOC;
			}
			set
			{
				if ((this._TUONG_TAC_THUOC != value))
				{
					this.OnTUONG_TAC_THUOCChanging(value);
					this.SendPropertyChanging();
					this._TUONG_TAC_THUOC = value;
					this.SendPropertyChanged("TUONG_TAC_THUOC");
					this.OnTUONG_TAC_THUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEU_KIEN_BAO_QUAN", DbType="NVarChar(100)")]
		public string DIEU_KIEN_BAO_QUAN
		{
			get
			{
				return this._DIEU_KIEN_BAO_QUAN;
			}
			set
			{
				if ((this._DIEU_KIEN_BAO_QUAN != value))
				{
					this.OnDIEU_KIEN_BAO_QUANChanging(value);
					this.SendPropertyChanging();
					this._DIEU_KIEN_BAO_QUAN = value;
					this.SendPropertyChanged("DIEU_KIEN_BAO_QUAN");
					this.OnDIEU_KIEN_BAO_QUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHONG_CHI_DINH", DbType="NVarChar(MAX)")]
		public string CHONG_CHI_DINH
		{
			get
			{
				return this._CHONG_CHI_DINH;
			}
			set
			{
				if ((this._CHONG_CHI_DINH != value))
				{
					this.OnCHONG_CHI_DINHChanging(value);
					this.SendPropertyChanging();
					this._CHONG_CHI_DINH = value;
					this.SendPropertyChanged("CHONG_CHI_DINH");
					this.OnCHONG_CHI_DINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAC_DUNG_PHU", DbType="NVarChar(MAX)")]
		public string TAC_DUNG_PHU
		{
			get
			{
				return this._TAC_DUNG_PHU;
			}
			set
			{
				if ((this._TAC_DUNG_PHU != value))
				{
					this.OnTAC_DUNG_PHUChanging(value);
					this.SendPropertyChanging();
					this._TAC_DUNG_PHU = value;
					this.SendPropertyChanged("TAC_DUNG_PHU");
					this.OnTAC_DUNG_PHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHAM_VI_PHAN_PHOI", DbType="NVarChar(MAX)")]
		public string PHAM_VI_PHAN_PHOI
		{
			get
			{
				return this._PHAM_VI_PHAN_PHOI;
			}
			set
			{
				if ((this._PHAM_VI_PHAN_PHOI != value))
				{
					this.OnPHAM_VI_PHAN_PHOIChanging(value);
					this.SendPropertyChanging();
					this._PHAM_VI_PHAN_PHOI = value;
					this.SendPropertyChanged("PHAM_VI_PHAN_PHOI");
					this.OnPHAM_VI_PHAN_PHOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XUAT_XU", DbType="NVarChar(200)")]
		public string XUAT_XU
		{
			get
			{
				return this._XUAT_XU;
			}
			set
			{
				if ((this._XUAT_XU != value))
				{
					this.OnXUAT_XUChanging(value);
					this.SendPropertyChanging();
					this._XUAT_XU = value;
					this.SendPropertyChanged("XUAT_XU");
					this.OnXUAT_XUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DUOCPHAM_CHI_TIET_DUOCPHAM", Storage="_DUOCPHAM", ThisKey="ID_DUOCPHAM", OtherKey="ID_DUOCPHAM", IsForeignKey=true)]
		public DUOCPHAM DUOCPHAM
		{
			get
			{
				return this._DUOCPHAM.Entity;
			}
			set
			{
				DUOCPHAM previousValue = this._DUOCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._DUOCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DUOCPHAM.Entity = null;
						previousValue.CHI_TIET_DUOCPHAMs.Remove(this);
					}
					this._DUOCPHAM.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_DUOCPHAMs.Add(this);
						this._ID_DUOCPHAM = value.ID_DUOCPHAM;
					}
					else
					{
						this._ID_DUOCPHAM = default(int);
					}
					this.SendPropertyChanged("DUOCPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CHUCVU;
		
		private string _TEN_CHUCVU;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CHUCVUChanging(int value);
    partial void OnID_CHUCVUChanged();
    partial void OnTEN_CHUCVUChanging(string value);
    partial void OnTEN_CHUCVUChanged();
    #endregion
		
		public CHUCVU()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CHUCVU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CHUCVU
		{
			get
			{
				return this._ID_CHUCVU;
			}
			set
			{
				if ((this._ID_CHUCVU != value))
				{
					this.OnID_CHUCVUChanging(value);
					this.SendPropertyChanging();
					this._ID_CHUCVU = value;
					this.SendPropertyChanged("ID_CHUCVU");
					this.OnID_CHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_CHUCVU", DbType="NVarChar(100)")]
		public string TEN_CHUCVU
		{
			get
			{
				return this._TEN_CHUCVU;
			}
			set
			{
				if ((this._TEN_CHUCVU != value))
				{
					this.OnTEN_CHUCVUChanging(value);
					this.SendPropertyChanging();
					this._TEN_CHUCVU = value;
					this.SendPropertyChanged("TEN_CHUCVU");
					this.OnTEN_CHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIEN", Storage="_NHANVIENs", ThisKey="ID_CHUCVU", OtherKey="ID_CHUCVU")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHMUC")]
	public partial class DANHMUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DANHMUC;
		
		private string _TEN_DANHMUC;
		
		private string _GHICHU;
		
		private EntitySet<DUOCPHAM> _DUOCPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DANHMUCChanging(int value);
    partial void OnID_DANHMUCChanged();
    partial void OnTEN_DANHMUCChanging(string value);
    partial void OnTEN_DANHMUCChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public DANHMUC()
		{
			this._DUOCPHAMs = new EntitySet<DUOCPHAM>(new Action<DUOCPHAM>(this.attach_DUOCPHAMs), new Action<DUOCPHAM>(this.detach_DUOCPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DANHMUC", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_DANHMUC
		{
			get
			{
				return this._ID_DANHMUC;
			}
			set
			{
				if ((this._ID_DANHMUC != value))
				{
					this.OnID_DANHMUCChanging(value);
					this.SendPropertyChanging();
					this._ID_DANHMUC = value;
					this.SendPropertyChanged("ID_DANHMUC");
					this.OnID_DANHMUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DANHMUC", DbType="NVarChar(100)")]
		public string TEN_DANHMUC
		{
			get
			{
				return this._TEN_DANHMUC;
			}
			set
			{
				if ((this._TEN_DANHMUC != value))
				{
					this.OnTEN_DANHMUCChanging(value);
					this.SendPropertyChanging();
					this._TEN_DANHMUC = value;
					this.SendPropertyChanged("TEN_DANHMUC");
					this.OnTEN_DANHMUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(200)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUC_DUOCPHAM", Storage="_DUOCPHAMs", ThisKey="ID_DANHMUC", OtherKey="ID_DANHMUC")]
		public EntitySet<DUOCPHAM> DUOCPHAMs
		{
			get
			{
				return this._DUOCPHAMs;
			}
			set
			{
				this._DUOCPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DUOCPHAMs(DUOCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUC = this;
		}
		
		private void detach_DUOCPHAMs(DUOCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DUOCPHAM")]
	public partial class DUOCPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DUOCPHAM;
		
		private string _TEN_DUOCPHAM;
		
		private int _ID_LOAIDUOCPHAM;
		
		private int _ID_DANHMUC;
		
		private string _KETOA;
		
		private System.Nullable<System.DateTime> _NGAY_NGUNG_BAN_THUOC;
		
		private string _HINHANH;
		
		private string _TINHTRANG;
		
		private System.Nullable<decimal> _GIA;
		
		private string _GHICHU;
		
		private EntitySet<CT_HOADON> _CT_HOADONs;
		
		private EntitySet<CT_PHIEUNHAPKHO> _CT_PHIEUNHAPKHOs;
		
		private EntitySet<CHI_TIET_DUOCPHAM> _CHI_TIET_DUOCPHAMs;
		
		private EntityRef<DANHMUC> _DANHMUC;
		
		private EntityRef<LOAIDUOCPHAM> _LOAIDUOCPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DUOCPHAMChanging(int value);
    partial void OnID_DUOCPHAMChanged();
    partial void OnTEN_DUOCPHAMChanging(string value);
    partial void OnTEN_DUOCPHAMChanged();
    partial void OnID_LOAIDUOCPHAMChanging(int value);
    partial void OnID_LOAIDUOCPHAMChanged();
    partial void OnID_DANHMUCChanging(int value);
    partial void OnID_DANHMUCChanged();
    partial void OnKETOAChanging(string value);
    partial void OnKETOAChanged();
    partial void OnNGAY_NGUNG_BAN_THUOCChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_NGUNG_BAN_THUOCChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnTINHTRANGChanging(string value);
    partial void OnTINHTRANGChanged();
    partial void OnGIAChanging(System.Nullable<decimal> value);
    partial void OnGIAChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public DUOCPHAM()
		{
			this._CT_HOADONs = new EntitySet<CT_HOADON>(new Action<CT_HOADON>(this.attach_CT_HOADONs), new Action<CT_HOADON>(this.detach_CT_HOADONs));
			this._CT_PHIEUNHAPKHOs = new EntitySet<CT_PHIEUNHAPKHO>(new Action<CT_PHIEUNHAPKHO>(this.attach_CT_PHIEUNHAPKHOs), new Action<CT_PHIEUNHAPKHO>(this.detach_CT_PHIEUNHAPKHOs));
			this._CHI_TIET_DUOCPHAMs = new EntitySet<CHI_TIET_DUOCPHAM>(new Action<CHI_TIET_DUOCPHAM>(this.attach_CHI_TIET_DUOCPHAMs), new Action<CHI_TIET_DUOCPHAM>(this.detach_CHI_TIET_DUOCPHAMs));
			this._DANHMUC = default(EntityRef<DANHMUC>);
			this._LOAIDUOCPHAM = default(EntityRef<LOAIDUOCPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DUOCPHAM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DUOCPHAM
		{
			get
			{
				return this._ID_DUOCPHAM;
			}
			set
			{
				if ((this._ID_DUOCPHAM != value))
				{
					this.OnID_DUOCPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_DUOCPHAM = value;
					this.SendPropertyChanged("ID_DUOCPHAM");
					this.OnID_DUOCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DUOCPHAM", DbType="NVarChar(100)")]
		public string TEN_DUOCPHAM
		{
			get
			{
				return this._TEN_DUOCPHAM;
			}
			set
			{
				if ((this._TEN_DUOCPHAM != value))
				{
					this.OnTEN_DUOCPHAMChanging(value);
					this.SendPropertyChanging();
					this._TEN_DUOCPHAM = value;
					this.SendPropertyChanged("TEN_DUOCPHAM");
					this.OnTEN_DUOCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIDUOCPHAM", DbType="Int NOT NULL")]
		public int ID_LOAIDUOCPHAM
		{
			get
			{
				return this._ID_LOAIDUOCPHAM;
			}
			set
			{
				if ((this._ID_LOAIDUOCPHAM != value))
				{
					if (this._LOAIDUOCPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LOAIDUOCPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIDUOCPHAM = value;
					this.SendPropertyChanged("ID_LOAIDUOCPHAM");
					this.OnID_LOAIDUOCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DANHMUC", DbType="Int NOT NULL")]
		public int ID_DANHMUC
		{
			get
			{
				return this._ID_DANHMUC;
			}
			set
			{
				if ((this._ID_DANHMUC != value))
				{
					if (this._DANHMUC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DANHMUCChanging(value);
					this.SendPropertyChanging();
					this._ID_DANHMUC = value;
					this.SendPropertyChanged("ID_DANHMUC");
					this.OnID_DANHMUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KETOA", DbType="NVarChar(100)")]
		public string KETOA
		{
			get
			{
				return this._KETOA;
			}
			set
			{
				if ((this._KETOA != value))
				{
					this.OnKETOAChanging(value);
					this.SendPropertyChanging();
					this._KETOA = value;
					this.SendPropertyChanged("KETOA");
					this.OnKETOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_NGUNG_BAN_THUOC", DbType="Date")]
		public System.Nullable<System.DateTime> NGAY_NGUNG_BAN_THUOC
		{
			get
			{
				return this._NGAY_NGUNG_BAN_THUOC;
			}
			set
			{
				if ((this._NGAY_NGUNG_BAN_THUOC != value))
				{
					this.OnNGAY_NGUNG_BAN_THUOCChanging(value);
					this.SendPropertyChanging();
					this._NGAY_NGUNG_BAN_THUOC = value;
					this.SendPropertyChanged("NGAY_NGUNG_BAN_THUOC");
					this.OnNGAY_NGUNG_BAN_THUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="VarChar(300)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="NVarChar(100)")]
		public string TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="Money")]
		public System.Nullable<decimal> GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(250)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DUOCPHAM_CT_HOADON", Storage="_CT_HOADONs", ThisKey="ID_DUOCPHAM", OtherKey="ID_DUOCPHAM")]
		public EntitySet<CT_HOADON> CT_HOADONs
		{
			get
			{
				return this._CT_HOADONs;
			}
			set
			{
				this._CT_HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DUOCPHAM_CT_PHIEUNHAPKHO", Storage="_CT_PHIEUNHAPKHOs", ThisKey="ID_DUOCPHAM", OtherKey="ID_DUOCPHAM")]
		public EntitySet<CT_PHIEUNHAPKHO> CT_PHIEUNHAPKHOs
		{
			get
			{
				return this._CT_PHIEUNHAPKHOs;
			}
			set
			{
				this._CT_PHIEUNHAPKHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DUOCPHAM_CHI_TIET_DUOCPHAM", Storage="_CHI_TIET_DUOCPHAMs", ThisKey="ID_DUOCPHAM", OtherKey="ID_DUOCPHAM")]
		public EntitySet<CHI_TIET_DUOCPHAM> CHI_TIET_DUOCPHAMs
		{
			get
			{
				return this._CHI_TIET_DUOCPHAMs;
			}
			set
			{
				this._CHI_TIET_DUOCPHAMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUC_DUOCPHAM", Storage="_DANHMUC", ThisKey="ID_DANHMUC", OtherKey="ID_DANHMUC", IsForeignKey=true)]
		public DANHMUC DANHMUC
		{
			get
			{
				return this._DANHMUC.Entity;
			}
			set
			{
				DANHMUC previousValue = this._DANHMUC.Entity;
				if (((previousValue != value) 
							|| (this._DANHMUC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANHMUC.Entity = null;
						previousValue.DUOCPHAMs.Remove(this);
					}
					this._DANHMUC.Entity = value;
					if ((value != null))
					{
						value.DUOCPHAMs.Add(this);
						this._ID_DANHMUC = value.ID_DANHMUC;
					}
					else
					{
						this._ID_DANHMUC = default(int);
					}
					this.SendPropertyChanged("DANHMUC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIDUOCPHAM_DUOCPHAM", Storage="_LOAIDUOCPHAM", ThisKey="ID_LOAIDUOCPHAM", OtherKey="ID_LOAIDUOCPHAM", IsForeignKey=true)]
		public LOAIDUOCPHAM LOAIDUOCPHAM
		{
			get
			{
				return this._LOAIDUOCPHAM.Entity;
			}
			set
			{
				LOAIDUOCPHAM previousValue = this._LOAIDUOCPHAM.Entity;
				if (((previousValue != value) 
							|| (this._LOAIDUOCPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIDUOCPHAM.Entity = null;
						previousValue.DUOCPHAMs.Remove(this);
					}
					this._LOAIDUOCPHAM.Entity = value;
					if ((value != null))
					{
						value.DUOCPHAMs.Add(this);
						this._ID_LOAIDUOCPHAM = value.ID_LOAIDUOCPHAM;
					}
					else
					{
						this._ID_LOAIDUOCPHAM = default(int);
					}
					this.SendPropertyChanged("LOAIDUOCPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HOADONs(CT_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.DUOCPHAM = this;
		}
		
		private void detach_CT_HOADONs(CT_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.DUOCPHAM = null;
		}
		
		private void attach_CT_PHIEUNHAPKHOs(CT_PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.DUOCPHAM = this;
		}
		
		private void detach_CT_PHIEUNHAPKHOs(CT_PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.DUOCPHAM = null;
		}
		
		private void attach_CHI_TIET_DUOCPHAMs(CHI_TIET_DUOCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.DUOCPHAM = this;
		}
		
		private void detach_CHI_TIET_DUOCPHAMs(CHI_TIET_DUOCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.DUOCPHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_HOADON;
		
		private int _ID_NHANVIEN;
		
		private string _ID_KHACHHANG;
		
		private int _ID_LOAIHINH;
		
		private System.Nullable<System.DateTime> _NGAYGIAO;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
		private string _HINHANH;
		
		private System.Nullable<double> _THANHTIEN;
		
		private string _TRANGTHAI;
		
		private EntitySet<CT_HOADON> _CT_HOADONs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<LOAIHINH> _LOAIHINH;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_HOADONChanging(int value);
    partial void OnID_HOADONChanged();
    partial void OnID_NHANVIENChanging(int value);
    partial void OnID_NHANVIENChanged();
    partial void OnID_KHACHHANGChanging(string value);
    partial void OnID_KHACHHANGChanged();
    partial void OnID_LOAIHINHChanging(int value);
    partial void OnID_LOAIHINHChanged();
    partial void OnNGAYGIAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGIAOChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnTHANHTIENChanging(System.Nullable<double> value);
    partial void OnTHANHTIENChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public HOADON()
		{
			this._CT_HOADONs = new EntitySet<CT_HOADON>(new Action<CT_HOADON>(this.attach_CT_HOADONs), new Action<CT_HOADON>(this.detach_CT_HOADONs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._LOAIHINH = default(EntityRef<LOAIHINH>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HOADON", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_HOADON
		{
			get
			{
				return this._ID_HOADON;
			}
			set
			{
				if ((this._ID_HOADON != value))
				{
					this.OnID_HOADONChanging(value);
					this.SendPropertyChanging();
					this._ID_HOADON = value;
					this.SendPropertyChanged("ID_HOADON");
					this.OnID_HOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHANVIEN", DbType="Int NOT NULL")]
		public int ID_NHANVIEN
		{
			get
			{
				return this._ID_NHANVIEN;
			}
			set
			{
				if ((this._ID_NHANVIEN != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_NHANVIEN = value;
					this.SendPropertyChanged("ID_NHANVIEN");
					this.OnID_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KHACHHANG", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ID_KHACHHANG
		{
			get
			{
				return this._ID_KHACHHANG;
			}
			set
			{
				if ((this._ID_KHACHHANG != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._ID_KHACHHANG = value;
					this.SendPropertyChanged("ID_KHACHHANG");
					this.OnID_KHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIHINH", DbType="Int NOT NULL")]
		public int ID_LOAIHINH
		{
			get
			{
				return this._ID_LOAIHINH;
			}
			set
			{
				if ((this._ID_LOAIHINH != value))
				{
					if (this._LOAIHINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LOAIHINHChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIHINH = value;
					this.SendPropertyChanged("ID_LOAIHINH");
					this.OnID_LOAIHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGIAO", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYGIAO
		{
			get
			{
				return this._NGAYGIAO;
			}
			set
			{
				if ((this._NGAYGIAO != value))
				{
					this.OnNGAYGIAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYGIAO = value;
					this.SendPropertyChanged("NGAYGIAO");
					this.OnNGAYGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="VarChar(300)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Float")]
		public System.Nullable<double> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="NVarChar(100)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CT_HOADON", Storage="_CT_HOADONs", ThisKey="ID_HOADON", OtherKey="ID_HOADON")]
		public EntitySet<CT_HOADON> CT_HOADONs
		{
			get
			{
				return this._CT_HOADONs;
			}
			set
			{
				this._CT_HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_KHACHHANG", ThisKey="ID_KHACHHANG", OtherKey="ID_KHACHHANG", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._ID_KHACHHANG = value.ID_KHACHHANG;
					}
					else
					{
						this._ID_KHACHHANG = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHINH_HOADON", Storage="_LOAIHINH", ThisKey="ID_LOAIHINH", OtherKey="ID_LOAIHINH", IsForeignKey=true)]
		public LOAIHINH LOAIHINH
		{
			get
			{
				return this._LOAIHINH.Entity;
			}
			set
			{
				LOAIHINH previousValue = this._LOAIHINH.Entity;
				if (((previousValue != value) 
							|| (this._LOAIHINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIHINH.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._LOAIHINH.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._ID_LOAIHINH = value.ID_LOAIHINH;
					}
					else
					{
						this._ID_LOAIHINH = default(int);
					}
					this.SendPropertyChanged("LOAIHINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON", Storage="_NHANVIEN", ThisKey="ID_NHANVIEN", OtherKey="ID_NHANVIEN", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._ID_NHANVIEN = value.ID_NHANVIEN;
					}
					else
					{
						this._ID_NHANVIEN = default(int);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HOADONs(CT_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CT_HOADONs(CT_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_KHACHHANG;
		
		private string _HOTEN_KHACHHANG;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _DIACHI;
		
		private string _EMAIL;
		
		private string _SDT;
		
		private int _ID_LOAIKHACHHANG;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
		private EntityRef<LOAIKHACHHANG> _LOAIKHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_KHACHHANGChanging(string value);
    partial void OnID_KHACHHANGChanged();
    partial void OnHOTEN_KHACHHANGChanging(string value);
    partial void OnHOTEN_KHACHHANGChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnID_LOAIKHACHHANGChanging(int value);
    partial void OnID_LOAIKHACHHANGChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			this._LOAIKHACHHANG = default(EntityRef<LOAIKHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KHACHHANG", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_KHACHHANG
		{
			get
			{
				return this._ID_KHACHHANG;
			}
			set
			{
				if ((this._ID_KHACHHANG != value))
				{
					this.OnID_KHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._ID_KHACHHANG = value;
					this.SendPropertyChanged("ID_KHACHHANG");
					this.OnID_KHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_KHACHHANG", DbType="NVarChar(100)")]
		public string HOTEN_KHACHHANG
		{
			get
			{
				return this._HOTEN_KHACHHANG;
			}
			set
			{
				if ((this._HOTEN_KHACHHANG != value))
				{
					this.OnHOTEN_KHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._HOTEN_KHACHHANG = value;
					this.SendPropertyChanged("HOTEN_KHACHHANG");
					this.OnHOTEN_KHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(10)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIKHACHHANG", DbType="Int NOT NULL")]
		public int ID_LOAIKHACHHANG
		{
			get
			{
				return this._ID_LOAIKHACHHANG;
			}
			set
			{
				if ((this._ID_LOAIKHACHHANG != value))
				{
					if (this._LOAIKHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LOAIKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIKHACHHANG = value;
					this.SendPropertyChanged("ID_LOAIKHACHHANG");
					this.OnID_LOAIKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_HOADONs", ThisKey="ID_KHACHHANG", OtherKey="ID_KHACHHANG")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_KHACHHANG", Storage="_TAIKHOAN", ThisKey="EMAIL", OtherKey="ID_USER", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._EMAIL = value.ID_USER;
					}
					else
					{
						this._EMAIL = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIKHACHHANG_KHACHHANG", Storage="_LOAIKHACHHANG", ThisKey="ID_LOAIKHACHHANG", OtherKey="ID_LOAIKHACHHANG", IsForeignKey=true)]
		public LOAIKHACHHANG LOAIKHACHHANG
		{
			get
			{
				return this._LOAIKHACHHANG.Entity;
			}
			set
			{
				LOAIKHACHHANG previousValue = this._LOAIKHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._LOAIKHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIKHACHHANG.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._LOAIKHACHHANG.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._ID_LOAIKHACHHANG = value.ID_LOAIKHACHHANG;
					}
					else
					{
						this._ID_LOAIKHACHHANG = default(int);
					}
					this.SendPropertyChanged("LOAIKHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIDUOCPHAM")]
	public partial class LOAIDUOCPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOAIDUOCPHAM;
		
		private string _TEN_LOAIDUOCPHAM;
		
		private EntitySet<DUOCPHAM> _DUOCPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOAIDUOCPHAMChanging(int value);
    partial void OnID_LOAIDUOCPHAMChanged();
    partial void OnTEN_LOAIDUOCPHAMChanging(string value);
    partial void OnTEN_LOAIDUOCPHAMChanged();
    #endregion
		
		public LOAIDUOCPHAM()
		{
			this._DUOCPHAMs = new EntitySet<DUOCPHAM>(new Action<DUOCPHAM>(this.attach_DUOCPHAMs), new Action<DUOCPHAM>(this.detach_DUOCPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIDUOCPHAM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_LOAIDUOCPHAM
		{
			get
			{
				return this._ID_LOAIDUOCPHAM;
			}
			set
			{
				if ((this._ID_LOAIDUOCPHAM != value))
				{
					this.OnID_LOAIDUOCPHAMChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIDUOCPHAM = value;
					this.SendPropertyChanged("ID_LOAIDUOCPHAM");
					this.OnID_LOAIDUOCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAIDUOCPHAM", DbType="NVarChar(100)")]
		public string TEN_LOAIDUOCPHAM
		{
			get
			{
				return this._TEN_LOAIDUOCPHAM;
			}
			set
			{
				if ((this._TEN_LOAIDUOCPHAM != value))
				{
					this.OnTEN_LOAIDUOCPHAMChanging(value);
					this.SendPropertyChanging();
					this._TEN_LOAIDUOCPHAM = value;
					this.SendPropertyChanged("TEN_LOAIDUOCPHAM");
					this.OnTEN_LOAIDUOCPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIDUOCPHAM_DUOCPHAM", Storage="_DUOCPHAMs", ThisKey="ID_LOAIDUOCPHAM", OtherKey="ID_LOAIDUOCPHAM")]
		public EntitySet<DUOCPHAM> DUOCPHAMs
		{
			get
			{
				return this._DUOCPHAMs;
			}
			set
			{
				this._DUOCPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DUOCPHAMs(DUOCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAIDUOCPHAM = this;
		}
		
		private void detach_DUOCPHAMs(DUOCPHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAIDUOCPHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIHINH")]
	public partial class LOAIHINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOAIHINH;
		
		private string _TEN_LOAIHINH;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOAIHINHChanging(int value);
    partial void OnID_LOAIHINHChanged();
    partial void OnTEN_LOAIHINHChanging(string value);
    partial void OnTEN_LOAIHINHChanged();
    #endregion
		
		public LOAIHINH()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIHINH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LOAIHINH
		{
			get
			{
				return this._ID_LOAIHINH;
			}
			set
			{
				if ((this._ID_LOAIHINH != value))
				{
					this.OnID_LOAIHINHChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIHINH = value;
					this.SendPropertyChanged("ID_LOAIHINH");
					this.OnID_LOAIHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAIHINH", DbType="NVarChar(100)")]
		public string TEN_LOAIHINH
		{
			get
			{
				return this._TEN_LOAIHINH;
			}
			set
			{
				if ((this._TEN_LOAIHINH != value))
				{
					this.OnTEN_LOAIHINHChanging(value);
					this.SendPropertyChanging();
					this._TEN_LOAIHINH = value;
					this.SendPropertyChanged("TEN_LOAIHINH");
					this.OnTEN_LOAIHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHINH_HOADON", Storage="_HOADONs", ThisKey="ID_LOAIHINH", OtherKey="ID_LOAIHINH")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHINH = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIKHACHHANG")]
	public partial class LOAIKHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOAIKHACHHANG;
		
		private string _TEN_LOAIKHACHHANG;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOAIKHACHHANGChanging(int value);
    partial void OnID_LOAIKHACHHANGChanged();
    partial void OnTEN_LOAIKHACHHANGChanging(string value);
    partial void OnTEN_LOAIKHACHHANGChanged();
    #endregion
		
		public LOAIKHACHHANG()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIKHACHHANG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LOAIKHACHHANG
		{
			get
			{
				return this._ID_LOAIKHACHHANG;
			}
			set
			{
				if ((this._ID_LOAIKHACHHANG != value))
				{
					this.OnID_LOAIKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIKHACHHANG = value;
					this.SendPropertyChanged("ID_LOAIKHACHHANG");
					this.OnID_LOAIKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAIKHACHHANG", DbType="NVarChar(100)")]
		public string TEN_LOAIKHACHHANG
		{
			get
			{
				return this._TEN_LOAIKHACHHANG;
			}
			set
			{
				if ((this._TEN_LOAIKHACHHANG != value))
				{
					this.OnTEN_LOAIKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._TEN_LOAIKHACHHANG = value;
					this.SendPropertyChanged("TEN_LOAIKHACHHANG");
					this.OnTEN_LOAIKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIKHACHHANG_KHACHHANG", Storage="_KHACHHANGs", ThisKey="ID_LOAIKHACHHANG", OtherKey="ID_LOAIKHACHHANG")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIKHACHHANG = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIKHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_NHACUNGCAP;
		
		private string _TEN_NHACUNGCAP;
		
		private string _DIACHI;
		
		private EntitySet<PHIEUNHAPKHO> _PHIEUNHAPKHOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NHACUNGCAPChanging(int value);
    partial void OnID_NHACUNGCAPChanged();
    partial void OnTEN_NHACUNGCAPChanging(string value);
    partial void OnTEN_NHACUNGCAPChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._PHIEUNHAPKHOs = new EntitySet<PHIEUNHAPKHO>(new Action<PHIEUNHAPKHO>(this.attach_PHIEUNHAPKHOs), new Action<PHIEUNHAPKHO>(this.detach_PHIEUNHAPKHOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHACUNGCAP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_NHACUNGCAP
		{
			get
			{
				return this._ID_NHACUNGCAP;
			}
			set
			{
				if ((this._ID_NHACUNGCAP != value))
				{
					this.OnID_NHACUNGCAPChanging(value);
					this.SendPropertyChanging();
					this._ID_NHACUNGCAP = value;
					this.SendPropertyChanged("ID_NHACUNGCAP");
					this.OnID_NHACUNGCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_NHACUNGCAP", DbType="NVarChar(100)")]
		public string TEN_NHACUNGCAP
		{
			get
			{
				return this._TEN_NHACUNGCAP;
			}
			set
			{
				if ((this._TEN_NHACUNGCAP != value))
				{
					this.OnTEN_NHACUNGCAPChanging(value);
					this.SendPropertyChanging();
					this._TEN_NHACUNGCAP = value;
					this.SendPropertyChanged("TEN_NHACUNGCAP");
					this.OnTEN_NHACUNGCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_PHIEUNHAPKHO", Storage="_PHIEUNHAPKHOs", ThisKey="ID_NHACUNGCAP", OtherKey="ID_NHACUNGCAP")]
		public EntitySet<PHIEUNHAPKHO> PHIEUNHAPKHOs
		{
			get
			{
				return this._PHIEUNHAPKHOs;
			}
			set
			{
				this._PHIEUNHAPKHOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUNHAPKHOs(PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_PHIEUNHAPKHOs(PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_NHANVIEN;
		
		private string _HOTEN_NHANVIEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private System.Nullable<System.DateTime> _NGAYVAOLAM;
		
		private string _HINHANH;
		
		private string _DIACHI;
		
		private string _EMAIL;
		
		private string _SDT;
		
		private int _ID_CHUCVU;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntityRef<CHUCVU> _CHUCVU;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NHANVIENChanging(int value);
    partial void OnID_NHANVIENChanged();
    partial void OnHOTEN_NHANVIENChanging(string value);
    partial void OnHOTEN_NHANVIENChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNGAYVAOLAMChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYVAOLAMChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnID_CHUCVUChanging(int value);
    partial void OnID_CHUCVUChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._CHUCVU = default(EntityRef<CHUCVU>);
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHANVIEN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_NHANVIEN
		{
			get
			{
				return this._ID_NHANVIEN;
			}
			set
			{
				if ((this._ID_NHANVIEN != value))
				{
					this.OnID_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._ID_NHANVIEN = value;
					this.SendPropertyChanged("ID_NHANVIEN");
					this.OnID_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_NHANVIEN", DbType="NVarChar(100)")]
		public string HOTEN_NHANVIEN
		{
			get
			{
				return this._HOTEN_NHANVIEN;
			}
			set
			{
				if ((this._HOTEN_NHANVIEN != value))
				{
					this.OnHOTEN_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN_NHANVIEN = value;
					this.SendPropertyChanged("HOTEN_NHANVIEN");
					this.OnHOTEN_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(10)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYVAOLAM", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYVAOLAM
		{
			get
			{
				return this._NGAYVAOLAM;
			}
			set
			{
				if ((this._NGAYVAOLAM != value))
				{
					this.OnNGAYVAOLAMChanging(value);
					this.SendPropertyChanging();
					this._NGAYVAOLAM = value;
					this.SendPropertyChanged("NGAYVAOLAM");
					this.OnNGAYVAOLAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="VarChar(300)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CHUCVU", DbType="Int NOT NULL")]
		public int ID_CHUCVU
		{
			get
			{
				return this._ID_CHUCVU;
			}
			set
			{
				if ((this._ID_CHUCVU != value))
				{
					if (this._CHUCVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CHUCVUChanging(value);
					this.SendPropertyChanging();
					this._ID_CHUCVU = value;
					this.SendPropertyChanged("ID_CHUCVU");
					this.OnID_CHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON", Storage="_HOADONs", ThisKey="ID_NHANVIEN", OtherKey="ID_NHANVIEN")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIEN", Storage="_CHUCVU", ThisKey="ID_CHUCVU", OtherKey="ID_CHUCVU", IsForeignKey=true)]
		public CHUCVU CHUCVU
		{
			get
			{
				return this._CHUCVU.Entity;
			}
			set
			{
				CHUCVU previousValue = this._CHUCVU.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._CHUCVU.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._ID_CHUCVU = value.ID_CHUCVU;
					}
					else
					{
						this._ID_CHUCVU = default(int);
					}
					this.SendPropertyChanged("CHUCVU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_NHANVIEN", Storage="_TAIKHOAN", ThisKey="EMAIL", OtherKey="ID_USER", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._EMAIL = value.ID_USER;
					}
					else
					{
						this._EMAIL = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAPKHO")]
	public partial class PHIEUNHAPKHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PHIEUNHAPKHO;
		
		private System.Nullable<int> _ID_NHACUNGCAP;
		
		private System.Nullable<System.DateTime> _NGAYNHAPKHO;
		
		private string _NHANVIEN;
		
		private EntitySet<CT_PHIEUNHAPKHO> _CT_PHIEUNHAPKHOs;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PHIEUNHAPKHOChanging(int value);
    partial void OnID_PHIEUNHAPKHOChanged();
    partial void OnID_NHACUNGCAPChanging(System.Nullable<int> value);
    partial void OnID_NHACUNGCAPChanged();
    partial void OnNGAYNHAPKHOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHAPKHOChanged();
    partial void OnNHANVIENChanging(string value);
    partial void OnNHANVIENChanged();
    #endregion
		
		public PHIEUNHAPKHO()
		{
			this._CT_PHIEUNHAPKHOs = new EntitySet<CT_PHIEUNHAPKHO>(new Action<CT_PHIEUNHAPKHO>(this.attach_CT_PHIEUNHAPKHOs), new Action<CT_PHIEUNHAPKHO>(this.detach_CT_PHIEUNHAPKHOs));
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PHIEUNHAPKHO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PHIEUNHAPKHO
		{
			get
			{
				return this._ID_PHIEUNHAPKHO;
			}
			set
			{
				if ((this._ID_PHIEUNHAPKHO != value))
				{
					this.OnID_PHIEUNHAPKHOChanging(value);
					this.SendPropertyChanging();
					this._ID_PHIEUNHAPKHO = value;
					this.SendPropertyChanged("ID_PHIEUNHAPKHO");
					this.OnID_PHIEUNHAPKHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NHACUNGCAP", DbType="Int")]
		public System.Nullable<int> ID_NHACUNGCAP
		{
			get
			{
				return this._ID_NHACUNGCAP;
			}
			set
			{
				if ((this._ID_NHACUNGCAP != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NHACUNGCAPChanging(value);
					this.SendPropertyChanging();
					this._ID_NHACUNGCAP = value;
					this.SendPropertyChanged("ID_NHACUNGCAP");
					this.OnID_NHACUNGCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAPKHO", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYNHAPKHO
		{
			get
			{
				return this._NGAYNHAPKHO;
			}
			set
			{
				if ((this._NGAYNHAPKHO != value))
				{
					this.OnNGAYNHAPKHOChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAPKHO = value;
					this.SendPropertyChanged("NGAYNHAPKHO");
					this.OnNGAYNHAPKHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN", DbType="NVarChar(100)")]
		public string NHANVIEN
		{
			get
			{
				return this._NHANVIEN;
			}
			set
			{
				if ((this._NHANVIEN != value))
				{
					this.OnNHANVIENChanging(value);
					this.SendPropertyChanging();
					this._NHANVIEN = value;
					this.SendPropertyChanged("NHANVIEN");
					this.OnNHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAPKHO_CT_PHIEUNHAPKHO", Storage="_CT_PHIEUNHAPKHOs", ThisKey="ID_PHIEUNHAPKHO", OtherKey="ID_PHIEUNHAPKHO")]
		public EntitySet<CT_PHIEUNHAPKHO> CT_PHIEUNHAPKHOs
		{
			get
			{
				return this._CT_PHIEUNHAPKHOs;
			}
			set
			{
				this._CT_PHIEUNHAPKHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_PHIEUNHAPKHO", Storage="_NHACUNGCAP", ThisKey="ID_NHACUNGCAP", OtherKey="ID_NHACUNGCAP", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.PHIEUNHAPKHOs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPKHOs.Add(this);
						this._ID_NHACUNGCAP = value.ID_NHACUNGCAP;
					}
					else
					{
						this._ID_NHACUNGCAP = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_PHIEUNHAPKHOs(CT_PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAPKHO = this;
		}
		
		private void detach_CT_PHIEUNHAPKHOs(CT_PHIEUNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAPKHO = null;
		}
	}
}
#pragma warning restore 1591
